name: giveawayboat
on:
  push:
    branches:
      - master
jobs:
  giveawayboat:
    name: giveawayboat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
        - run: npm install
        - run: npm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TOKEN: ${{ secrets.DISCORD_TOKEN }}
