name: npm-start
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    name: npm-start
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: '12'
        check-latest: true
    - name: Run
    - run: npm install && npm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TOKEN: ${{ secrets.DISCORD_TOKEN }}
